version: '3.9'
services:
  nginx:
      image: nginx:latest
      container_name: nginx
      restart: always
      ports:
      - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - backend
        - frontend
      networks:
        - cloudmart-network
  
  backend:
    image: viniciuspoa2/cloudmart-backend:latest
    container_name: backend
    restart: always
    environment:
      AWS_REGION: us-east-1
      BEDROCK_AGENT_ID: ${BEDROCK_AGENT_ID}
      BEDROCK_AGENT_ALIAS_ID: ${BEDROCK_AGENT_ALIAS_ID}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ASSISTANT_ID: ${OPENAI_ASSISTANT_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    networks:
      - cloudmart-network
    ports:
      - 5000:5000

  frontend:
    image: viniciuspoa2/cloudmart-frontend:13067150846
    container_name: frontend
    restart: always
    depends_on:
      - backend
    networks:
      - cloudmart-network
  
networks:
  cloudmart-network:
    driver: bridge
