version: '3.9'

services:  
  backend:
    image: viniciuspoa2/cloudmart-backend:latest
    container_name: backend
    restart: always
    environment:
      - AWS_REGION=us-east-1
      - BEDROCK_AGENT_ID=<seu-bedrock-agent-id>
      - BEDROCK_AGENT_ALIAS_ID=<seu-bedrock-agent-alias-id>
      - OPENAI_API_KEY=<sua-chave-api-openai>
      - OPENAI_ASSISTANT_ID=<seu-id-assistente-openai>
    ports:
      - 5000:5000

  frontend:
    image: viniciuspoa2/cloudmart-frontend:latest
    container_name: frontend
    environment:
      - VITE_API_BASE_URL=http://backend:5000/api
    ports:
      - 5001:5001
